### ISSUE TITLE
关于服务器做了http跳转https端口问题

### ISSUE THREAD

**Issue by jacksonjim** [bugfan/i996#12]
关于服务器做了http跳转https端口
比如http 是8000  https 8443
使用公众配置的8000 但是访问二级域名时出现https://xxx.i9996.me:8443 访问不了，目前有没有办法做到配置端口一段范围 8000-8443或8000，8443；
目前配置一台NAS时做了http跳转https的，这个管理面页内部做了强制的跳转

**Comment by bugfan** [comment]
一个用户最多分配一个tcp端口；且如果不用那个tcp端口只能使用https 443 或者http 80来（通过host区分用户）

**Comment by jacksonjim** [comment]
好吧，那可能也没什么大用处
