### ISSUE TITLE
一个奇怪的现象

### ISSUE THREAD

**Issue by babizhu** [bugfan/i996#15]
提交的get请求可以返回内容
但是post请求就会超时

**Comment by bugfan** [comment]
post有问题是不是使用的v1?就是v1.i996.me或者i996.me那个域？
v1在某些情况下，post会有转义问题，这个因为curl限制无解啦，，，（或者以后我在修修）

你用v2启动应该没问题的

**Comment by bugfan** [comment]
但是v1比v2稳定一些

**Comment by babizhu** [comment]
谢谢，我试试
