### ISSUE TITLE
关于 终端断线自动重连，这个是自动的吗

### ISSUE THREAD

**Issue by wg5946** [bugfan/i996#16]
win10使用v2命令，目前发现运行一段时间后cmd窗口就自动关闭了，请问下应该如何实现 终端断线自动重连？

**Comment by bugfan** [comment]
cmd窗口自动关闭，程序也会自动关闭。

v1,v2都是通过脚本启动，排除人为原因中断之外，脚本会尝试重连10次，如果还没连接上就中断了。

如果你自己会编程，可以把脚本改造一下来实现。

或者，你也可以用那个客户端的方式去链接 https://www.i996.me/#/download ，只需打赏点钱就行了😂
