### ISSUE TITLE
额话说域名能绑定自己的吗？

### ISSUE THREAD

**Issue by bzy-080408** [bugfan/i996#6]
如题，我自己有个域名，想在家里面建个online judge供学校社团使用，想绑定自己的域名，顺便说一下，域名没备案所以我阿里的服务器绑定不了。。。

**Comment by bugfan** [comment]
你回复cname:自己域名就行呀，好好读一下公众号返回的信息，看看怎么用，很简单。

**Comment by bzy-080408** [comment]
...抱歉当时没仔细看，不过是只能给一条线吗？我需要搭建一个oj加blog，需要两条线

**Comment by bugfan** [comment]
> ...抱歉当时没仔细看，不过是只能给一条线吗？我需要搭建一个oj加blog，需要两条线

一个微信号关注了只给一条线，你可以用其他微信号关注，在获取一个
